name: Terraform apply
on:
    push:
        branches: 
            - main      
        paths: 
            - terraform/**
    workflow_dispatch: 
jobs:    
    plan:
        name: Terraform plan
        runs-on: ubuntu-latest    
        permissions: 
            id-token: write
            contents: read        
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: Configure AWS credentials from Test account
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: secret.aws_access_key
                aws-secret-access-key: secret.aws_secret_access_key
                aws-region: secret.aws_region
            - name: setupTerraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: "1.6.5"
            - run: cd terraform
            - name: Terraform fmt
              id: fmt
              run: terraform fmt -check              
            - name: Terraform Init
              id: init
              run: terraform init              
            - name: Terraform Validate
              id: validate
              run: terraform validate -no-color              
            - name: Terraform Plan
              id: plan
              run: terraform plan -no-color
